### ISSUE TITLE
redesign EmergencyBottomSheet

### ISSUE THREAD

**Issue by DasProffi** [helpwave/mobile-app#60]

**Comment by JannikWibker** [comment]
<img width="414" alt="Screenshot 2022-11-06 at 13 57 13" src="https://user-images.githubusercontent.com/16372321/200905782-16ceceac-1bfb-44e0-b6ab-b92a4ca02291.png">

The chips for displaying "Geschlossen/Offen" and the different facilities look pretty indistinguishable, as the first one is by far the most important one it should be easily distinguishable.
*My recommendations*:
- add a divider after "Geschlossen/Offen"
- make the facility chips either a single color or choose far more pale colors for them
- make the text of the "Geschlossen/Offen" chip actually white instead of the light grey it currently is
- make the text of the "Geschlossen/Offen" chip bold (font weight 500 should do)

the padding between the address label and the actual address is too little, should be the same as with "weitere Funktionen" and the first text below it, *recommendations*:
- the 4 actions under "weitere Funktionen" are pretty far apart from each other, they could be closer together
- they should also somehow show wether they are actions or not
- not sure if red for actions is a good choice, could maybe also experiment with white underlined text

buttons at the bottom:
- the buttons at the bottom are a bit too wide for my taste, if possible they could be made smaller (this could be a bit hard with long button text however; if it doesn't work out just leave it as is)
- the space between the 2 buttons could be a bit bigger

there are also a lot of different font sizes in use on this screen, if this can be reduced somewhat easily doing so would be great

**Comment by DasProffi** [comment]
Done in #68
